# Include from sshd_config. Create redstm-inbox with /usr/sbin/nologin.
Match User redstm-inbox
    ChrootDirectory /srv/redstm-text-inbox
    ForceCommand internal-sftp -u 0027 -d /
    AuthenticationMethods publickey
    AuthorizedKeysFile /etc/ssh/authorized_keys/%u
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitTTY no
    AllowTcpForwarding no
    X11Forwarding no
    AllowAgentForwarding no
    PermitTunnel no
