BOT_NAME = "redstm"

SPIDER_MODULES = ["crawler.spiders"]
NEWSPIDER_MODULE = "crawler.spiders"

ROBOTSTXT_OBEY = True
USER_AGENT = "ReDSTM/0.1 (+personal archival tool; single user)"
CONCURRENT_REQUESTS = 1
CONCURRENT_REQUESTS_PER_DOMAIN = 1
DOWNLOAD_DELAY = 10.0
DOWNLOAD_TIMEOUT = 180
RANDOMIZE_DOWNLOAD_DELAY = False
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 10.0
AUTOTHROTTLE_MAX_DELAY = 60.0
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
RETRY_TIMES = 2
RETRY_HTTP_CODES = [408, 500, 502, 503, 504, 522, 524]
DOWNLOAD_WARNSIZE = 8 << 20
DOWNLOAD_MAXSIZE = 64 << 20
DOWNLOAD_FAIL_ON_DATALOSS = False
COOKIES_ENABLED = True
TELNETCONSOLE_ENABLED = False
LOG_LEVEL = "INFO"

DOWNLOADER_MIDDLEWARES = {"crawler.middlewares.WarcCaptureMiddleware": 595}
ITEM_PIPELINES = {"crawler.archive_pipeline.ArchivePipeline": 300}
REDSTM_WARC_PATH = ".data/warc/capture.warc.gz"
REDSTM_WARC_MAX_BYTES = 1 << 30
REDSTM_FRONTIER_LEASE_SECONDS = 900
REDSTM_LISTING_TIMEOUT_SECONDS = 120

REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
FEED_EXPORT_ENCODING = "utf-8"
