/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 690da699ffdb2177e14c3b071fb58765)
interface __BaseEnv_Env {
	ARCHIVE: R2Bucket;
	CONTROL_DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	TEAM_DOMAIN: "https://redstm-archive-private.cloudflareaccess.com";
	POLICY_AUD: "fe751d9940fe39ebdf36da5a3e5d3465ef206eb3c59e98f537c5c6df817c0604";
	RUNNER_POLICY_AUD: "16713ca6268190096ef46bf4b6e23d2f6086d62da50ea2ea138752a6e3612a17";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEAM_DOMAIN" | "POLICY_AUD" | "RUNNER_POLICY_AUD">> {}
}
